#!/usr/bin/env bash
#=========================================================================
# 05-synopsys-vcs-baglsim
#=========================================================================

# Stop on error and echo all commands

set -e
trap 'echo "CMD: $BASH_COMMAND"' DEBUG

# Colors

RED="\e[31m"
GREEN="\e[32m"
RESET="\e[0m"

# Determine RUNDIR and TOPDIR

RUNDIR="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"
TOPDIR="$(readlink -f $RUNDIR/../../..)"

cd $RUNDIR

#-------------------------------------------------------------------------
# Function for running one sim
#-------------------------------------------------------------------------
# $1 = name of test

function run_sim
{
  trap 'echo "CMD: $BASH_COMMAND"' DEBUG

  rm -rf $1 $1.daidir $1.log

  vcs -sverilog -xprop=tmerge -override_timescale=1ns/1ps -top Top \
    +neg_tchk +sdfverbose \
    -sdf max:Top.DUT:../04-cadence-innovus-pnr/post-pnr.sdf \
    +define+CYCLE_TIME={{clock_period}} \
    +define+VTB_INPUT_DELAY=0.025 \
    +define+VTB_OUTPUT_DELAY=0.025 \
    +vcs+dumpvars+$1.vcd \
    -o $1 \
    +incdir+$TOPDIR/sim/build \
    ${ECE6745_STDCELLS}/stdcells.v \
    $TOPDIR/sim/build/$1_tb.v \
    ../04-cadence-innovus-pnr/post-pnr.v | tee run.log

  ./$1 | tee -a $1.log

  vcd2saif -input ./$1.vcd -output ./$1.saif | tee -a $1.log

  if grep "\[ passed \]" $1.log > /dev/null 2>&1; then
    echo -e ">>>> [ ${GREEN}passed${RESET} ] $1" >> $1.log
  else
    echo -e ">>>> [ ${RED}FAILED${RESET} ] $1" >> $1.log
  fi
}

#-------------------------------------------------------------------------
# List of tests and evals
#-------------------------------------------------------------------------

{% set tests_and_evals = (tests | default([])) + (evals | default([])) -%}

{% for item in tests_and_evals -%}
run_sim {{item}}
{% endfor %}

#-------------------------------------------------------------------------
# Print results
#-------------------------------------------------------------------------

echo "" > run.log

{% for item in tests_and_evals -%}
grep -h ">>>" {{item}}.log | sed -e 's/>>>>//' >> run.log
{% endfor %}

echo "" >> run.log

cat run.log

