#!/usr/bin/env bash
#=========================================================================
# 04-cadence-innovus-pnr
#=========================================================================

# Stop on error and echo all commands

set -e
trap 'echo "CMD: $BASH_COMMAND"' DEBUG

# Determine RUNDIR and TOPDIR

RUNDIR="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))"
TOPDIR="$(readlink -f $RUNDIR/../../..)"

cd $RUNDIR

# Run using run.tcl script

innovus -no_gui -files run.tcl | tee run.log

